#:schema node_modules/wrangler/config-schema.json
name = "cache-worker"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
PRIVATE_COOKIE_NAMES = ["terranil_session", "terranilToken"]
CLIENT_PREFS_COOKIE_NAME = "terranilmwclientpreferences"
CLIENT_PREFS_CLASS_PREFIXES = ["skin-theme-clientpref-", "vector-feature-limited-width-clientpref-", "vector-feature-page-tools-pinned-clientpref-"]
PAGE_TTL = 86400
MISSING_PAGE_TTL = 3600
CACHED_NAMESPACES = ["", "Category", "Project", "Terra_Nil_Wiki"]
