#:schema node_modules/wrangler/config-schema.json
name = "cache-worker"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
PRIVATE_COOKIE_NAMES = ["utdr-_session", "utdr-Token"]
CLIENT_PREFS_COOKIE_NAME = "utdr-mwclientpreferences"
CLIENT_PREFS_CLASS_PREFIXES = ["skin-theme-clientpref-", "vector-feature-limited-width-clientpref-", "vector-feature-page-tools-pinned-clientpref-"]
PAGE_TTL = 600
MISSING_PAGE_TTL = 60
CACHED_NAMESPACES = ["", "Category", "Project", "Undertale_Wiki", "Deltarune_Wiki"]
